# директория etc/nginx главнее ссылки через sites-available/enabled для nginx conf
worker_processes auto;


events {
}

http {  
        map $http_upgrade $connection_upgrade {
            default upgrade;
            ''      close;
        }
       
   
server {
                listen       443 ssl http2;
                server_name fff.engbot.ru;
                root  /usr/share/nginx/html;
                index index.php index.html;

				# мы уже примонтировали сертификаты в Docker Compose
                ssl_certificate     /etc/nginx/cert.pem;
                ssl_certificate_key /etc/nginx/key.pem;

                
                
                



                location /bot {
                proxy_pass http://bot:3000;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection $connection_upgrade;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

                proxy_buffering off;
                proxy_cache off;
                proxy_redirect off;
                        
            }
		        location /handleStatus {
                proxy_pass http://bot:3000;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection $connection_upgrade;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

                proxy_buffering off;
                proxy_cache off;
                proxy_redirect off;    
            }
		    




                location / {
                    try_files $uri $uri/ /index.html;
                    # for css being read correctly(error `text/plain` mimetype)
                    include /etc/nginx/mime.types; 
                }

                location ~ /\.ht {
                deny all;
                }


     }
       
}
